remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Jesus Gazol Condon - Software Engineer, Technologist, Leader - Bergen, Norway
description: Jesus Gazol Condon is a software engineer, technologist and leader based in Bergen, Norway. He is a passionate advocate of open source software and a strong believer in the power of technology to improve people's lives.

